title: Brisas del Mar
description: Oceanfront living in Manglaralto, Ecuador
baseurl: ""
url: "https://spondylus.tech"

# Build
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
