title: Brisas del Mar
description: Oceanfront living in Manglaralto, Ecuador
baseurl: "/spondylus-tech"
url: ""

# Build
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
